### ISSUE TITLE
Find most similar nodes

### ISSUE THREAD

**Issue by ghost** [thibaudmartinez/node2vec#1]
I'd like to have per each nodes the most similar based on embedding.
In the node2vec python library by SNAP: https://snap.stanford.edu/node2vec/
We can do that:
```
for node, _ in node2vec_model.most_similar('2302108'):                               
    print(node)
```
But using this library I got an error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-25-a7cd17929993> in <module>
----> 1 for node, _ in node2vec_model.most_similar('2302108'):
      2     print(node)

AttributeError: 'Node2Vec' object has no attribute 'most_similar'
```

**Comment by thibaudmartinez** [comment]
Hi there,

Thanks for your message.

This functionality is not currently supported in the library.

I'm going to think about including it in a future release.

In the meantime, you could use [Scikit-Learn DistanceMetric](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.DistanceMetric.html) on the node embeddings to achieve what you want.
