### ISSUE TITLE
Not working in Python 3.9

### ISSUE THREAD

**Issue by ferzcam** [thibaudmartinez/node2vec#2]
I tried to use the library with Python 3.9 but it seems that the .whl file is not supported in that version. I changed to Python 3.7 and it worked well. 
Is there any plan to release .whl files for the latest Python versions?

**Comment by thibaudmartinez** [comment]
I created a new release with wheels for Python 3.7, 3.8, and 3.9: https://github.com/thibaudmartinez/node2vec/releases/tag/v0.2.0.

You can install the wheel for Python 3.9 with:
```
pip install https://github.com/thibaudmartinez/node2vec/releases/download/v0.2.0/node2vec-0.1.0-cp39-cp39-linux_x86_64.whl
```

**Comment by ferzcam** [comment]
Thank you. This helps a lot. However, I would like to suggest just one more thing: it would be great if the dependencies can also be updated. So for example, instead of using gensim=3.8.3 we can use gensim>4.*.

**Comment by thibaudmartinez** [comment]
gensim version 4 breaks compatibility with the previous major version, so it's a bit cumbersome to update. I'll try to update it when I get some time. In the meantime, if you really need the latest version of gensim, feel free to make a pull request 🙂.
